#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pangomm
Version  : 2.50.1
Release  : 15
URL      : https://download.gnome.org/sources/pangomm/2.50/pangomm-2.50.1.tar.xz
Source0  : https://download.gnome.org/sources/pangomm/2.50/pangomm-2.50.1.tar.xz
Summary  : C++ binding for Pango
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: pangomm-lib = %{version}-%{release}
Requires: pangomm-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : pkgconfig(cairomm-1.16)
BuildRequires : pkgconfig(glibmm-2.68)
BuildRequires : pkgconfig(mm-common-libstdc++)
BuildRequires : pkgconfig(pangocairo)

%description
This directory contains files not tracked by a source code control program,
The files can have one of two origins.

%package dev
Summary: dev components for the pangomm package.
Group: Development
Requires: pangomm-lib = %{version}-%{release}
Provides: pangomm-devel = %{version}-%{release}
Requires: pangomm = %{version}-%{release}

%description dev
dev components for the pangomm package.


%package lib
Summary: lib components for the pangomm package.
Group: Libraries
Requires: pangomm-license = %{version}-%{release}

%description lib
lib components for the pangomm package.


%package license
Summary: license components for the pangomm package.
Group: Default

%description license
license components for the pangomm package.


%prep
%setup -q -n pangomm-2.50.1
cd %{_builddir}/pangomm-2.50.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663789733
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/pangomm
cp %{_builddir}/pangomm-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pangomm/cf756914ec51f52f9c121be247bfda232dc6afd2 || :
cp %{_builddir}/pangomm-%{version}/COPYING.tools %{buildroot}/usr/share/package-licenses/pangomm/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib64/pangomm-2.48/proc/m4/convert.m4
/usr/lib64/pangomm-2.48/proc/m4/convert_pango.m4
/usr/lib64/pangomm-2.48/proc/m4/convert_pangomm.m4

%files dev
%defattr(-,root,root,-)
/usr/include/pangomm-2.48/pangomm.h
/usr/include/pangomm-2.48/pangomm/attributes.h
/usr/include/pangomm-2.48/pangomm/attriter.h
/usr/include/pangomm-2.48/pangomm/attrlist.h
/usr/include/pangomm-2.48/pangomm/cairofontmap.h
/usr/include/pangomm-2.48/pangomm/cairofontmapimpl.h
/usr/include/pangomm-2.48/pangomm/color.h
/usr/include/pangomm-2.48/pangomm/context.h
/usr/include/pangomm-2.48/pangomm/coverage.h
/usr/include/pangomm-2.48/pangomm/font.h
/usr/include/pangomm-2.48/pangomm/fontdescription.h
/usr/include/pangomm-2.48/pangomm/fontface.h
/usr/include/pangomm-2.48/pangomm/fontfamily.h
/usr/include/pangomm-2.48/pangomm/fontmap.h
/usr/include/pangomm-2.48/pangomm/fontmetrics.h
/usr/include/pangomm-2.48/pangomm/fontset.h
/usr/include/pangomm-2.48/pangomm/glyph.h
/usr/include/pangomm-2.48/pangomm/glyphitem.h
/usr/include/pangomm-2.48/pangomm/glyphstring.h
/usr/include/pangomm-2.48/pangomm/init.h
/usr/include/pangomm-2.48/pangomm/item.h
/usr/include/pangomm-2.48/pangomm/language.h
/usr/include/pangomm-2.48/pangomm/layout.h
/usr/include/pangomm-2.48/pangomm/layoutiter.h
/usr/include/pangomm-2.48/pangomm/layoutline.h
/usr/include/pangomm-2.48/pangomm/private/attributes_p.h
/usr/include/pangomm-2.48/pangomm/private/attriter_p.h
/usr/include/pangomm-2.48/pangomm/private/attrlist_p.h
/usr/include/pangomm-2.48/pangomm/private/cairofontmap_p.h
/usr/include/pangomm-2.48/pangomm/private/color_p.h
/usr/include/pangomm-2.48/pangomm/private/context_p.h
/usr/include/pangomm-2.48/pangomm/private/coverage_p.h
/usr/include/pangomm-2.48/pangomm/private/font_p.h
/usr/include/pangomm-2.48/pangomm/private/fontdescription_p.h
/usr/include/pangomm-2.48/pangomm/private/fontface_p.h
/usr/include/pangomm-2.48/pangomm/private/fontfamily_p.h
/usr/include/pangomm-2.48/pangomm/private/fontmap_p.h
/usr/include/pangomm-2.48/pangomm/private/fontmetrics_p.h
/usr/include/pangomm-2.48/pangomm/private/fontset_p.h
/usr/include/pangomm-2.48/pangomm/private/glyph_p.h
/usr/include/pangomm-2.48/pangomm/private/glyphitem_p.h
/usr/include/pangomm-2.48/pangomm/private/glyphstring_p.h
/usr/include/pangomm-2.48/pangomm/private/item_p.h
/usr/include/pangomm-2.48/pangomm/private/language_p.h
/usr/include/pangomm-2.48/pangomm/private/layout_p.h
/usr/include/pangomm-2.48/pangomm/private/layoutiter_p.h
/usr/include/pangomm-2.48/pangomm/private/layoutline_p.h
/usr/include/pangomm-2.48/pangomm/private/rectangle_p.h
/usr/include/pangomm-2.48/pangomm/private/renderer_p.h
/usr/include/pangomm-2.48/pangomm/private/tabarray_p.h
/usr/include/pangomm-2.48/pangomm/rectangle.h
/usr/include/pangomm-2.48/pangomm/renderer.h
/usr/include/pangomm-2.48/pangomm/tabarray.h
/usr/include/pangomm-2.48/pangomm/types.h
/usr/include/pangomm-2.48/pangomm/wrap_init.h
/usr/lib64/libpangomm-2.48.so
/usr/lib64/pangomm-2.48/include/pangommconfig.h
/usr/lib64/pkgconfig/pangomm-2.48.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpangomm-2.48.so.1
/usr/lib64/libpangomm-2.48.so.1.0.30

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pangomm/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/pangomm/cf756914ec51f52f9c121be247bfda232dc6afd2
